### ISSUE TITLE
Local actor templates are not overwriting global templates

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/ays9#106]
#### Installation information

- jumpscale version: Development from master branch and ays9 from ays_tests branch
- operating system: Development env using docker on an Ubuntu 16.04 system

#### Detailed description
One of the ays tests [test_directory_structure.yaml] was failing - details can be found [here](https://travis-ci.org/Jumpscale/ays9/builds/252032223) - after investigating, it truns out that executing the test blueprint fails while creating a cockpit service with the following error:
```
(js9) root@js9:~/gig/code/github/jumpscale/ays9/tests/sample_repo1# ays blueprint
[Tue11 00:03] - SystemProcess.py    :661 :j.sal.process                  - INFO     - Checking whether at least 1 processes redis-server are running
error during execution of the blueprint bp_related1.yaml: ERROR: The arguments passed to the service cockpit|cockpitv1 contains the following errors: 
- Invalid parameter [description] passed while creating cockpit!cockpitv1.

- Invalid parameter [datacenter] passed while creating cockpit!cockpitv1.

DataSchema : 
@0x886cc4c01082ae4d;
struct Schema {
        hostNode @0 :Text;
        flist @1 :Text = "https://stor.jumpscale.org/stor2/flist/aysbuild/jumpscale.flist";
        dnsSshkey @2 :Text;
        domain @3 :Text;
        botClient @4 :Text;
        botSecret @5 :Text;
        oauthOrganization @6 :Text;
        oauthClientId @7 :Text;
        oauthClientSecret @8 :Text;
        oauthJwtKey @9 :Text;
        caddyEmail @10 :Text;
        caddyStagging @11 :Bool = false;

}
 ((type:input.error)

``` 
The blue print is trying to create a cockpit service and a local template of the cockpit actor template is defined in the repository
```
(js9) root@js9:~/gig/code/github/jumpscale/ays9/tests/sample_repo1# cat actorTemplates/cockpit/config.yaml 
doc:
  property:
  - description: ''
  - datacenter: ''
links:
  parent:
    auto: false
    optional: false
    role: datacenter
recurring: []
```

#### Steps to reproduce
- Update ays9 branch to ays_tests in a working js9 system
- Restart your ays server
- Move to the repository sample_repo1 (/opt/code/github/jumpscale/ays9/tests/sample_repo1)
- Execute ays blueprint
