### ISSUE TITLE
Double entries in the services tree as shown in the AYS portal

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#202]
#### Installation information

- jumpscale version: 9.1.1
- operating system: JS9/Docker

#### Detailed description

When executing the below blueprints - all at onces - you get to see the following in the AYS Portal:

![wrong](https://user-images.githubusercontent.com/13795109/29824569-347c8b62-8cd2-11e7-857e-3892d0f90bc9.jpg)

The first entry should not be there, it should only be shown once,  as a child of `vdcfarm!auto_37`.

#### Steps to reproduce

Here are the blueprints, created by Artilium:

**client.yaml**:
```yaml
g8client__ilXk5JJ97bBDiCjsT66d:
  url: 'be-gen-1.demo.greenitglobe.com'
  login: 'artiliumadmin'
  password: '****'
  account: 'DemoReseller'
actions:
  - action: install
    actor: g8client
    service: ilXk5JJ97bBDiCjsT66d
```

**vdc.yaml**:
```yaml
vdc__tuesday1:
  g8client: 'ilXk5JJ97bBDiCjsT66d'
  location: 'be-gen-1'
  maxMemoryCapacity: 10
  maxDiskCapacity: 100
  maxCPUCapacity: 10
  maxNumPublicIP: 10
  account: 'DemoReseller'
  uservdc:
    - name: 'dSJQ91Ld0X'
      accesstype: 'ACDRUX'

actions:
  - action: install
    actor: vdc
    service: tuesday1
```

***uservdc.yaml***:
```yaml
uservdc__dSJQ91Ld0X:
  g8client: 'ilXk5JJ97bBDiCjsT66d'
  email: 'gig@bliep.nl'
  provider: 'itsyouonline'
actions:
  - action: install
    actor: uservdc
    service: dSJQ91Ld0X
````

**vm.yaml**:
```yaml
node.ovc__Vds0SExEYYC4Zh4xKAVm:
  vdc: "tuesday1"
  bootdiskSize: 50
  memory: 8
  osImage: Ubuntu 14.04 x64

actions:
  - action: install
```

#### Relevant stacktraces

n/a
