### ISSUE TITLE
VDC actor template doesn't allow to pass account names with spaces

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#206]
#### Installation information

- jumpscale version: master
- operating system: js9/docker

#### Detailed description

When executing the below blueprint, you get the error:
```bash
error during execution of the blueprint vdc.yaml:
ERROR:
Service instance name should be digits or alphanumeric.
you passed [Account of Yves] ((type:input.error)
```

So we don't support accounts that has spaces in its name? If so, how are we supposed to manage this kind of accounts through AYS?

It doesn't make sense that we support creating accounts with spaces in its name through the Cloud Broker Portal, but don't allow you to use them in AYS blueprints.

So:
- Or we disabling creating of Accounts with spaces in the name at the level of OpenvCloud
- Or we allow passing account names with spaces in blueprints

What we have now will lead to support issues => cost

Even if we decide not support spaces, the error message is still misleading, it complains about the `service instance name`, while the actual service instance name is `vdc4arne`...

#### Steps to reproduce

```yaml
vdc__vdc4arne:
  g8client: myg8
  location: be-gen-1
  account: "Account of Yves"
  uservdc:
    - name: arne
      accesstype: ACDRUX
```
