### ISSUE TITLE
Remove the [me] section from jumpscale9.toml

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#216]
#### Installation information

- jumpscale version: master/all

#### Detailed description

Following `[me]` section is in the default AYS configuration file, `/optvar/cfg/jumpscale9.toml`:
```toml
[me]
fullname = "Kristof De Spiegeleer"
loginname = "despiegk"
```

Since not used, please remove.
