### ISSUE TITLE
Creating another disk on existing vm is not there in the portal however the ays status is okay

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/ays9#272]
#### Installation information

- jumpscale version: 9.1.3
- operating system: ubuntu 16

#### Detailed description
1 - Execute this blueprint 
```
g8client__env:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'ah-elsayed'
    password: 'abc123456'
    account: 'john444'

vdc__vdc2:
    description: 'vdc for demo'
    g8client: 'env'
    account: 'john444'
    location: 'du-conv-2'

disk.ovc__disk2:
   size: 5
   g8client: 'env'
   description: 'data disk'
   type: 'D'
   maxIOPS: 600
   location: 'du-conv-2'

# create the vm.
# expose ports 22. Map it to 2210.
node.ovc__demo2:
    bootdisk.size: 50
    memory: 2
    os.image: 'Ubuntu 16.04 x64'
    ports:
        - '2210:22'
    disk:
      - 'disk2'

actions:
  - action: install

```
2- Execute this blueprint again but with different disk (ex: disk1)
     -  the ays run staus is ok
3- This disk won't be created in the portal
![disks](https://user-images.githubusercontent.com/15011431/30783347-d4667f92-a141-11e7-9599-48804b1963eb.png)

#### Steps to reproduce

provided in description.
