### ISSUE TITLE
Can't run AYS in production

### ISSUE THREAD

**Issue by xmonader** [Jumpscale/ays9#28]
#### Installation information

- jumpscale version: 9.0.0
- operating system: Linux/Ubuntu

#### Detailed description
Installing AYS9 in production
```
    def configure(self, production=False, client_secret='', client_id='', organization='', redirect_address='locahost:5000'):
        C = """
        production: {}
        oauth:
           jwt_key: "-----BEGIN PUBLIC KEY-----\\nMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAES5X8XrfKdx9gYayFITc89wad4usrk0n2\\n7MjiGYvqalizeSWTHEpnd7oea9IQ8T5oJjMVH5cc0H5tFSKilFFeh//wngxIyny6\\n6+Vq5t5B0V0Ehy01+2ceEon2Y0XDkIKv\\n-----END PUBLIC KEY-----\\n"
           client_secret: "{}"
           redirect_uri: "http://{}"
           client_id: "{}"
           organization: "{}"
        """.format(production, client_secret, redirect_address, client_id, organization)
        self.core.file_write("$JSCFGDIR/ays.yaml", C)
```
writes ays.yaml file
```
In [8]: j.application.config.get('ays')

In [9]: cat /optvar/cfg/jumpscale/ays.yaml
production: True
oauth:
   jwt_key: "-----BEGIN PUBLIC KEY-----\nMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAES5X8XrfKdx9gYayFITc89wad4usrk0n2\n7MjiGYvqalizeSWTHEpnd7oea9IQ8T5oJjMVH5cc0H5tFSKilFFeh//wngxIyny6\n6+Vq5t5B0V0Ehy01+2ceEon2Y0XDkIKv\n-----END PUBLIC KEY-----\n"
   client_secret: "***"
   redirect_uri: "http://172.17.0.2:5000"
   client_id: "***"
   organization: "***"

```
In 8.2.0 config `j.application.config` was instance of Config class
```

class Config:

    def __getattribute__(self, attr):
        config = {}
        config_files=[f.path for f in os.scandir(j.dirs.JSCFGDIR) if f.is_file()]
        # config_files = [f.path for f in os.scandir(config_path) if f.is_file()]
        for config_file in config_files:
            # support yaml, hrd, toml
            if config_file.endswith('.yaml'):
                with open(config_file, 'r') as conf:
                    cfg = yaml.load(conf)
            elif config_file.endswith('.hrd'):
                cfg = j.data.hrd.get(config_file)
                cfg = cfg.getHRDAsDict()
            else:
                cfg = j.sal.fs.fileGetContents(config_file)  # TODO support more common formats
            config[os.path.basename(config_file).split('.')[0]] = cfg
        return config

```
