### ISSUE TITLE
node.docker fails with KeyError: 'me', but succeeds when auto-retrying

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#324]
#### Installation information

- jumpscale version: master
- operating system: ubuntu 16.04 VM

#### Detailed description

We get a KeyError at the first run, but when it automatically retries later, it seems to succeed.

I'd be good to understand why and to investigate how it can succeed in the first run.

#### Steps to reproduce

First we execute the following blueprint and start a run:

```yaml
g8client__g8:
  url: 'se-gen-1.demo.greenitglobe.com'
  jwt: '<...>'
  account: 'myaccount'

vdc__vdc4partnerportal:
  g8client: 'g8'
  location: 'se-gen-1'

node.ovc__partnerportalhost:
    vdc: vdc4partnerportal
    bootdisk.size: 50
    memory: 2
    os.image: 'Ubuntu 16.04 x64'
    ports:
        - '2210:22'

app_docker__docker:
  os: 'partnerportalhost'

envvars__myvars:
  os: 'partnerportalhost'
  vstsAccount: 'account'
  vstsToken: 'pat'

actions:
  - action: install
````

No real problem, result as expected.

Then we execute the second blueprint:
```yaml
node.docker__vsts:
  os: 'partnerportalhost'
  image: 'microsoft/vsts-agent'

actions:
  - action: install
```

When starting a run we see this:

<img width="647" alt="screen shot 2017-10-10 at 21 41 25" src="https://user-images.githubusercontent.com/13795109/31406977-9371d1ca-ae03-11e7-91ed-a9a4291d2389.png">

Checking the logs:
```bash
In [49]: step1.jobs.list()
Out[49]: [job (4887bdf89a78bc095186e925e04443c2): node.docker!vsts.install() (running)]

In [50]: job=step1.jobs.get("4887bdf89a78bc095186e925e04443c2")

In [51]: job.logs.list()
Out[51]:
[{'category': 'trace', 'tags': '', 'epoch': 1507663698, 'log': "KeyError: 'me'", 'level': 1},
 {'category': 'trace', 'tags': '', 'epoch': 1507663718, 'log': "KeyError: 'me'", 'level': 1},
 {'category': 'errormsg', 'tags': '', 'epoch': 1507663718, 'log': 'Traceback (most recent call last):\n  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/tmp/actions/node.docker/b247d17a7fe0bec11ce6aafc6dd75f8c.py", line 69, in install\n    prefab.development.pip.install(\'docker-compose\')\n  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/development/PrefabPIP.py", line 58, in install\n    self.doneSet("pip_%s" % package)\n  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabBase.py", line 123, in doneSet\n    self.executor.configSave()\n  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 136, in configSave\n    self.state.configSave()\n  File "/opt/code/github/jumpscale/core9/JumpScale9/core/State.py", line 197, in configSave\n    cdict["me"]=self.config["me"]\nKeyError: \'me\'', 'level': 40}]
```

#### Relevant stacktraces

<img width="822" alt="screen shot 2017-10-10 at 21 44 00" src="https://user-images.githubusercontent.com/13795109/31407102-f4e99c3a-ae03-11e7-8bb4-606e0068eba4.png">
