### ISSUE TITLE
misleading populating of producers with same role

### ISSUE THREAD

**Issue by khaledkbadr** [Jumpscale/ays9#332]
#### Installation information

- jumpscale version: 9.2
- operating system: Ubuntu

#### Detailed description
If a service had in its config.yml two producers with the same role, the service producers will be populated with only the latest one

#### Steps to reproduce
I have a service with config.yml like below

```yml
links:
  consume:
    - auto: false
      min: 1
      max: 1
      role: storagecluster
      argname: blockCluster

    - auto: false
      min: 0
      max: 1
      role: storagecluster
      argname: objectCluster

    - auto: false
      min: 0
      max: 1
      role: storagecluster
      argname: slaveCluster
```

If I executed a blueprint 
```yml
vdiskstorage__myvdiskstorage:
  blockCluster: myblockcluster
  objectCluster: myobjectcluster
  slaveCluster: ""
```

It will add only the slavecluster (which is empty in this case)

![image](https://user-images.githubusercontent.com/6059889/31583979-c0a39d6a-b1ad-11e7-90d1-69bc5b961f12.png)
