### ISSUE TITLE
Account template to be updatable

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#71]
New limits may be defined, user ACLs can be updated

Corresponds to API:
 - /cloudapi/accounts/updateUser
 - /cloudapi/accounts/update

Note: Docs and tests must be included

part of #64

**Comment by islamTaha12** [comment]
verified with this bp:
```yaml

g8client__xtremx:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'xtremx'
    password: ''
    account: 'xtremx'

account__xtremx:
    maxMemoryCapacity: 32
    maxCPUCapacity: 10
    maxDiskCapacity: 1000
    maxNumPublicIP: 100

actions:
  - action: install
```

**Comment by islamTaha12** [comment]
Verified with this bp:

```yaml
g8client__xtremx:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'xtremx'
    password: ''

uservdc__usertest:
    password: 'test1234'
    email: 'fake@example.com'
    groups:
      - 'user'
    g8client: 'xtremx'

account__xtremx:
  accountusers:
      - name: 'usertest'
        accesstype: 'R'

```
