### ISSUE TITLE
VM template to add disk/detach disk

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#78]
Corresponds to API: 
 - /cloudapi/machines/addDisk
 - /cloudapi/machines/detachDisk

Docs and tests must be included

part of #64

**Comment by ahmedelsayed-93** [comment]
### blueprints
#### attach
```yaml
g8client__env:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'ah-elsayed'
    password: '<password>'
    account: '<account>'

vdc__cs1:
    location: 'du-conv-2'

disk.ovc__disk1:
    size: 7

node.ovc__demo:
    disk: 
      - disk1

actions:
    - action: install
```
#### detach
```yaml
node.ovc__demo:
    disk: []
```

### software version
master : 47b1b4a
