### ISSUE TITLE
VDC template to create VDC with limits

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#85]
Corresponds to API: 
 - /cloudapi/cloudspace/create

Docs and tests must be included

part of #64

**Comment by ahmedelsayed-93** [comment]
```yaml
g8client__env:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'ah-elsayed'
    password: '<pasword>'
    account: '<account>'


account__test_limits:
    maxMemoryCapacity: 2
    maxDiskCapacity: 15
    maxCPUCapacity: 2


vdc__cs1:
    description: 'test'
    g8client: 'env'
    location: 'du-conv-2'
    account: 'test_limits'
    maxMemoryCapacity: 2
    maxDiskCapacity: 15
    maxCPUCapacity: 2


node.ovc__demo:
    vdc: 'cs1'
    bootdisk.size: 10
    memory: 2
    os.image: 'Ubuntu 16.04 x64'


node.ovc__demo2:
    vdc: 'cs1'
    bootdisk.size: 10
    memory: 2
    os.image: 'Ubuntu 16.04 x64'

```

### software version 
master :  47b1b4ab
