### ISSUE TITLE
VDC template to delete VDC (uninstall)

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#87]
Corresponds to API: 
 - /cloudapi/cloudspaces/delete 

Docs and tests must be included

part of #64

**Comment by islamTaha12** [comment]
I used the following bp but it didnt delete the vdc
```yaml
g8client__xtremx:
    url: 'https://du-conv-2.demo.greenitglobe.com'
    login: 'xtremx'
    password: 'xtremx'
    account: 'xtremx'

vdc__xtremx:
    location: 'du-conv-2'

actions:
  - action: uninstall

```

**Comment by arahmanhamdy** [comment]
Are you sure that this cloudspace hasn't any active machines ?

**Comment by arahmanhamdy** [comment]
@islamTaha12 The url for g8client shouldn't have `https:// ` please remove it

**Comment by islamTaha12** [comment]
@arahmanhamdy still the same 
```yaml
g8client__xtremx:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'xtremx'
    password: 'xtremx'
    account: 'xtremx'

vdc__xtremx:
    location: 'du-conv-2'

actions:
  - action: uninstall

```
