### ISSUE TITLE
VDC template to add user/delete user/ update user access

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#88]
Corresponds to API: 
 - /cloudapi/cloudspaces/addUser 
 - /cloudapi/cloudspaces/deleteUser
 - /cloudapi/cloudspaces/updateUser

Docs and tests must be included

part of #64

**Comment by ahmedelsayed-93** [comment]
### Scenario 
- create vdc and add user **U1** to it with access right **ACDRUX** (for example)
- execute this 
```yaml
g8client__example:
    url: '<url of the environment>'
    login: '<username>'
    password: '<password>'
    account: '<account name>'

uservdc__U1:

vdc__vdcname:
    description: '<description>'
    g8client: 'example'
    account: '<account name>'
    location: '<name of the environment>'
    uservdc:
        - name: 'U1'
          accesstype: 'R'

actions:
  - action: install
```
### expected result 
user **U1** should have  access  type (**R**)

### actual result
**U1** still has access type **ACDRUX**
 

### software version
master : 47b1b4a
