### ISSUE TITLE
Error occurs when ays tried to delete cached file names

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/ays9#97]
Sometimes when I install some of the ays services in the 0-orchestrator repo I get the error below. I usually get over it by repeating the install until everything becomes in status 'Ok'.
The error is not consistent, however, it mostly occurs in the statsdb.
These are the services used:
https://github.com/zero-os/0-orchestrator/tree/master/templates

First I installed the node using the bp belw:
```
network.zero-os__storage:
  vlanTag: 101
  cidr: "192.168.66.0/24"

node.zero-os__54a9f715dbb1:
  redisAddr: 192.168.122.228
  redisPort: 6379
  hostname: "myg8ostwo"
  status: 'running'
  networks:
  - 'storage'

actions:
 - action: install

```

Then I installed statsdb service using the bp below and that's when the error occured:
```
statsdb__stats:
  node: '54a9f715dbb1'
  port: 9086

actions:
  - action: install

```

#### Relevant stacktraces

[Thu06 14:00] - Job.py              :57  :j.core.jobcontroller.job.e64f5996a5d2d336805fb867ef22aa06 - ERROR    - Traceback
 (most recent call last):
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 8, in sync
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 632, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 578, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-2321'.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/statsdb/d10e0380934dd244cf9fbed1c8ab2b41.py", line 205, in start
    j.tools.async.wrappers.sync(influxdb.executeAction('install', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 10, in sync
    loop = asyncio.new_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 642, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 593, in new_event_loop
    return self._loop_factory()
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 49, in __init__
    super().__init__(selector)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 55, in __init__
    self._make_self_pipe()
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 120, in _make_self_pipe
    self.add_reader(self._ssock.fileno(), self._read_from_self)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 232, in add_reader
    handle = events.Handle(callback, args, self)
  File "/usr/lib/python3.5/asyncio/events.py", line 91, in __init__
    self._source_traceback = traceback.extract_stack(sys._getframe(1))
  File "/usr/lib/python3.5/traceback.py", line 207, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/usr/lib/python3.5/traceback.py", line 354, in extract
    linecache.checkcache(filename)
  File "/usr/lib/python3.5/linecache.py", line 79, in checkcache
    del cache[filename]
